name: Deploy Wedding Quiz to Production

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Install dependencies, run lint and build application
        uses: actions/setup-node@master
        run: yarn install && yarn lint --fix && yarn build
      - name: Copy files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./*"
          target: /home/app/wedding-quiz/production
      - name: Start the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mv /home/app/wedding-quiz/.env.production /home/app/wedding-quiz/production/.env.production
            cd /home/app/wedding-quiz/production
            yarn start
