name: Deploy Wedding Quiz to Production

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploying to Production
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_API_URL: https://api.palpittero.com.br/api
      NEXT_PUBLIC_HASURA_GRAPHQL_URL: https://welcomed-swan-33.hasura.app/v1/graphql
      NEXT_PUBLIC_API_SECRET: ${{ secrets.NEXT_PUBLIC_API_SECRET }}
      NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY }}
      MAGIC_SECRET_KEY: ${{ secrets.MAGIC_SECRET_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@master
      - run: yarn install && yarn lint --fix && yarn build
      - name: Copy production dist files via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist/*"
          target: /var/www/palpittero.com.br/wedding-quiz
          strip_components: 1